name: tasty_cookpad
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shimmer: ^0.0.6
  rxdart: ^0.21.0
  firebase_messaging:
  firebase_core:
  connectivity: ^0.4.4
  firebase_database: ^3.0.4
  firebase_storage:
  giffy_dialog: ^1.3.0
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.12.7
  firebase_admob:
  image_picker:
  shared_preferences: 0.5.12+4
  eva_icons_flutter: ^2.0.0
  carousel_slider: ^2.0.0
  flutter_rating_bar: ^3.0.1+1
  flutter_inappwebview: ^4.0.0
  path_provider:
  image_crop: ^0.3.4
  camera:
  country_picker: ^1.0.4
  google_sign_in: ^4.5.6
  apple_sign_in: ^0.1.0
  provider: ^4.0.1
  in_app_purchase: ^0.3.4+16
  flutter_signin_button: ^1.1.0
  google_maps_flutter: ^0.5.26
  intl_phone_field: ^1.4.2
  badges: ^1.1.6
  uuid: 2.2.2
  share: ^0.6.5+4
  myfatoorah_flutter: ^1.0.12
  youtube_player_flutter: ^7.0.0+7


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family : DINPro-Bold
      fonts:
        - asset: assets/font/DINPro-Bold.ttf
    - family : Barlow
      fonts:
        - asset: assets/font/Barlow-Medium.ttf
    - family : Krungthep
      fonts:
        - asset: assets/font/Krungthep.ttf
    - family : WorkSans
      fonts:
        - asset: assets/font/WorkSans-Regular.ttf
    - family : Lemon
      fonts:
        - asset: assets/font/Lemon-Regular.ttf
          weight: 400
    - family : Sofia
      fonts:
        - asset: assets/font/Sofia/SofiaProBold.otf
          weight: 900
        - asset: assets/font/Sofia/SofiaProSemiBold.otf
          weight: 800
        - asset: assets/font/Sofia/SofiaProMedium.otf
          weight: 700
        - asset: assets/font/Sofia/SofiaProRegular.otf
          weight: 600
        - asset: assets/font/Sofia/SofiaProLight.otf
          weight: 500
        - asset: assets/font/Sofia/SofiaProExtraLight.otf
          weight: 400
        - asset: assets/font/Sofia/SofiaProUltraLight.otf
          weight: 300
    - family : Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-ExtraBold.otf
          weight: 900
        - asset: assets/font/Poppins/Poppins-Bold.otf
          weight: 800
        - asset: assets/font/Poppins/Poppins-SemiBold.otf
          weight: 700
        - asset: assets/font/Poppins/Poppins-Medium.otf
          weight: 600
        - asset: assets/font/Poppins/Poppins-Regular.otf
          weight: 500
        - asset: assets/font/Poppins/Poppins-Light.otf
          weight: 400
        - asset: assets/font/Poppins/Poppins-ExtraLight.otf
          weight: 300
        - asset: assets/font/Poppins/Poppins-Thin.otf
          weight: 200

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/tab/cart.png
    - assets/image/tab/cart_sel.png
    - assets/image/tab/event.png
    - assets/image/tab/event_sel.png
    - assets/image/tab/group.png
    - assets/image/tab/group_sel.png
    - assets/image/tab/live.png
    - assets/image/tab/live_sel.png
    - assets/image/tab/ticket.png
    - assets/image/tab/ticket_sel.png
    - assets/image/back.png
    - assets/image/yellowback.png
    - assets/image/love.png
    - assets/image/share.png
    - assets/image/ship_mark.png
    - assets/image/noticket.png
    - assets/image/editProfile.png
    - assets/image/phone.png
    - assets/image/editProfile.png
    - assets/image/logout.png
    - assets/image/noInternet.png
    - assets/image/edit-button.png
    - assets/image/cart.png
    - assets/image/sample/bag.png
    - assets/image/sample/bar_code.png
    - assets/image/shop/
    - assets/image/shopping-cart.png
    - assets/image/icon_cart.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
